Resources add & localisation missimg codes logger
spbu-coding-2023/graphs-graphs-8 pull request #21
Opened 2024-05-15 20:51 UTC by admitrievtsev

New:
- Localisation files are stored in Resources folder now
- Logging of missed localisation codes

2024-05-15 21:03 UTC, DedSec256 commented
Мб имелось в виду "**...missing** codes logger..."? :)

2024-05-16 12:01 UTC, admitrievtsev commented
> Мб имелось в виду "**...missing** codes logger..."? :)

Конечно, имелось ввиду -ing
Хотя, с другой стороны, герундий с окончанием на -img это интересная идея для шуточной версии локализации нашего интерфейса :)

2024-05-16 12:16 UTC, Ycyken requested changes

2024-05-16 12:16 UTC, Ycyken commented on composeApp/src/settings.json
> +{"language":"ru-RU"}
```suggestion
{"language":"en-US"}
```

2024-05-16 13:10 UTC, odiumuniverse approved these changes

2024-05-16 13:11 UTC, merged